name: Restore needed files

runs:
  using: composite
  steps:
    - name: Decode and create keystore file
      run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > ${GITHUB_WORKSPACE}/app/keystore.jks
    - name: Restore gradle properties
      run: |
        mkdir -p ~/.gradle/
        echo "KEYSTORE_FILE=${GITHUB_WORKSPACE}/app/keystore.jks" >> ~/.gradle/gradle.properties
        echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> ~/.gradle/gradle.properties
        echo "SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}" >> ~/.gradle/gradle.properties
        echo "SIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}" >> ~/.gradle/gradle.properties
        echo "FIREBASE_WEB_CLIENT_ID=${{ secrets.FIREBASE_WEB_CLIENT_ID }}" >> ~/.gradle/gradle.properties
      shell: bash
    - name: Restore google services json
      run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json