name: Restore needed files

description: |
  This action restores the keystore file, the google services json file and the gradle properties needed to build the app.

inputs:
  keystore_file:
    description: 'The keystore file encoded in base64'
    required: true
  keystore_password:
    description: 'The keystore password'
    required: true
  signing_key_alias:
    description: 'The signing key alias'
    required: true
  signing_key_password:
    description: 'The signing key password'
    required: true
  firebase_web_client_id:
    description: 'The firebase web client id'
    required: true
  google_services_json:
    description: 'The google services json file encoded in base64'
    required: true

runs:
  using: composite
  steps:
    - name: Restore keystore file
      run: echo "${{ inputs.keystore_file }}" | base64 --decode > ${GITHUB_WORKSPACE}/app/keystore.jks
      shell: bash
    - name: Restore gradle properties
      run: |
        mkdir -p ~/.gradle/
        echo "KEYSTORE_FILE=${GITHUB_WORKSPACE}/app/keystore.jks" >> ~/.gradle/gradle.properties
        echo "KEYSTORE_PASSWORD=${{ inputs.keystore_password }}" >> ~/.gradle/gradle.properties
        echo "SIGNING_KEY_ALIAS=${{ inputs.signing_key_alias }}" >> ~/.gradle/gradle.properties
        echo "SIGNING_KEY_PASSWORD=${{ inputs.signing_key_password }}" >> ~/.gradle/gradle.properties
        echo "FIREBASE_WEB_CLIENT_ID=${{ inputs.firebase_web_client_id }}" >> ~/.gradle/gradle.properties
      shell: bash
    - name: Restore google services json
      run: echo "${{ inputs.google_services_json }}" | base64 --decode > app/google-services.json
      shell: bash