name: Build, Test and Deploy

on:
  pull_request:
  push:
    branches:
      - 50-configure-cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Decode and create keystore file
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > ${GITHUB_WORKSPACE}/app/keystore.jks
      - name: Restore gradle properties
        run: |
          mkdir -p ~/.gradle/
          echo "KEYSTORE_FILE=${GITHUB_WORKSPACE}/app/keystore.jks" >> ~/.gradle/gradle.properties
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> ~/.gradle/gradle.properties
          echo "SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}" >> ~/.gradle/gradle.properties
          echo "SIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}" >> ~/.gradle/gradle.properties
          echo "FIREBASE_WEB_CLIENT_ID=${{ secrets.FIREBASE_WEB_CLIENT_ID }}" >> ~/.gradle/gradle.properties
        shell: bash
      - name: Restore google services json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json
      - name: Cache gradle properties
        uses: actions/cache@v2
        env:
            cache-name: cache-gradle-properties
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Cache google services json and keystore
        uses: actions/cache@v2
        env:
          cache-name: cache-google-files
        with:
          path: |
            app/google-services.json
            ${GITHUB_WORKSPACE}/app/keystore.jks
          key: ${{ runner.os }}-build-${{ env.cache-name }}
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run unit tests
        run: ./gradlew test --no-daemon --scan
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build release bundle
        run: ./gradlew bundleRelease
      #- name: Deploy to Play Store
      #  uses: r0adkll/upload-google-play@v1
      #  with:
      #    serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SECRET }}
      #    packageName: br.com.jwar.sharedbill
      #    releaseFiles: app/build/outputs/bundle/release/*.aab
      #    track: internal