name: Build, Test and Deploy

on:
  pull_request:
  push:
    branches:
      - 50-configure-cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Restore needed files
        uses: ./.github/actions/restore_files
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Restore needed files
        uses: ./.github/actions/restore_files
      - name: Run unit tests
        run: ./gradlew test --no-daemon --scan
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Restore needed files
        uses: ./.github/actions/restore_files
      - name: Build release bundle
        run: ./gradlew bundleRelease
      #- name: Deploy to Play Store
      #  uses: r0adkll/upload-google-play@v1
      #  with:
      #    serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SECRET }}
      #    packageName: br.com.jwar.sharedbill
      #    releaseFiles: app/build/outputs/bundle/release/*.aab
      #    track: internal