# Workflow name
name: Build, Test and Deploy

# When it will be triggered
on:
  pull_request:
  push:
    branches:
      - 50-configure-cicd

# Where it will run
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Decode keystore and create jks
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > keystore.jks
      - name: Restore gradle properties
        run: |
          mkdir -p ~/.gradle/
          echo "KEYSTORE_FILE=keystore.jks" >> ~/.gradle/gradle.properties
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> ~/.gradle/gradle.properties
          echo "SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}" >> ~/.gradle/gradle.properties
          echo "SIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}" >> ~/.gradle/gradle.properties
          echo "FIREBASE_WEB_CLIENT_ID=${{ secrets.FIREBASE_WEB_CLIENT_ID }}" >> ~/.gradle/gradle.properties
        shell: bash
      - name: show files
        run: ls
      - name: Create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > app/google-services.json
      - name: Run Unit Tests
        run: ./gradlew test --no-daemon --scan
      - name: Build App Bundle
        run: ./gradlew bundleRelease
      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SECRET }}
          packageName: br.com.jwar.sharedbill
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: internal