name: Build, Test and Deploy

on:
  pull_request:
  push:
    branches:
      - 50-configure-cicd

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup environment
        uses: ./.github/actions/setup
      - name: Restore needed files
        uses: ./.github/actions/restore_files
        with:
          keystore_file: ${{ secrets.KEYSTORE_FILE }}
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
          signing_key_alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          signing_key_password: ${{ secrets.SIGNING_KEY_PASSWORD }}
          firebase_web_client_id: ${{ secrets.FIREBASE_WEB_CLIENT_ID }}
          google_services_json: ${{ secrets.GOOGLE_SERVICES_JSON }}
      - name: Build
        run: ./gradlew build
      - name: Run unit tests
        run: ./gradlew test --no-daemon --scan
      - name: Build release bundle
        run: ./gradlew bundleRelease
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/bundle/release/*.aab
  deploy:
    name: Deploy to Play Store
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download bundle
        uses: actions/download-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/bundle/release/app-release.aab
      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SECRET }}
          packageName: br.com.jwar.sharedbill
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal